name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Create .env file
        run: |
          cat <<EOF > .env
          # Environment variables for the application
          AUTH_HOST=${{ secrets.AUTH_HOST }}
          USER_HOST=${{ secrets.USER_HOST }}
          PRODUCT_HOST=${{ secrets.PRODUCT_HOST }}
          ORDER_HOST=${{ secrets.ORDER_HOST }}

          # Ports for various services
          AUTH_PORT=${{ secrets.AUTH_PORT }}
          USER_PORT=${{ secrets.USER_PORT }}
          PRODUCT_PORT=${{ secrets.PRODUCT_PORT }}
          ORDER_PORT=${{ secrets.ORDER_PORT }}
          AUTH_GRPC_PORT=${{ secrets.AUTH_GRPC_PORT }}
          SWAGGER_PORT=${{ secrets.SWAGGER_PORT }}

          # PostgreSQL configuration
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}

          # Ports for various PostgreSQL services
          POSTGRES_AUTH_PORT=${{ secrets.POSTGRES_AUTH_PORT }}
          POSTGRES_USER_PORT=${{ secrets.POSTGRES_USER_PORT }}
          POSTGRES_PRODUCT_PORT=${{ secrets.POSTGRES_PRODUCT_PORT }}
          POSTGRES_ORDER_PORT=${{ secrets.POSTGRES_ORDER_PORT }}
          EOF

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Pull Docker Image
        run: |
              docker pull bukanasa/go-micro-services:auth-service-latest
              docker pull bukanasa/go-micro-services:order-service-latest
              docker pull bukanasa/go-micro-services:product-service-latest
              docker pull bukanasa/go-micro-services:user-service-latest

            
      - name: Stop and Remove Old Containers
        run: |
          docker compose --env-file ./.env -f ~/program/go-micro-services/docker/docker-compose.yml down --remove-orphans || true
      
      - name: Remove Old Docker Image
        run: |
          docker images --filter "reference=bukanasa/go-micro-services" --format "{{.ID}}" | xargs -r docker rmi -f || true
          
      - name: Run Docker
        run: |
          mv .env ~/program/go-micro-services 
          cd 
          cd program/go-micro-services
          docker compose --env-file .env -f docker/docker-compose.yml up -d
