name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Create .env file
        run: |
          cat <<EOF > .env
          # Environment variables for the application
          AUTH_HOST=${{ secrets.AUTH_HOST }}
          USER_HOST=${{ secrets.USER_HOST }}
          PRODUCT_HOST=${{ secrets.PRODUCT_HOST }}
          ORDER_HOST=${{ secrets.ORDER_HOST }}

          # Ports for various services
          AUTH_PORT=${{ secrets.AUTH_PORT }}
          USER_PORT=${{ secrets.USER_PORT }}
          PRODUCT_PORT=${{ secrets.PRODUCT_PORT }}
          ORDER_PORT=${{ secrets.ORDER_PORT }}
          AUTH_GRPC_PORT=${{ secrets.AUTH_GRPC_PORT }}
          SWAGGER_PORT=${{ secrets.SWAGGER_PORT }}

          # PostgreSQL configuration
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}

          # Ports for various PostgreSQL services
          POSTGRES_AUTH_PORT=${{ secrets.POSTGRES_AUTH_PORT }}
          POSTGRES_USER_PORT=${{ secrets.POSTGRES_USER_PORT }}
          POSTGRES_PRODUCT_PORT=${{ secrets.POSTGRES_PRODUCT_PORT }}
          POSTGRES_ORDER_PORT=${{ secrets.POSTGRES_ORDER_PORT }}
          EOF

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    

      - name: Stop and Remove Old Containers
        run: make down-prod

      - name: Remove Old Docker Images
        run: |
          echo "Removing unused images..."
          docker image prune -af || true

          echo "Removing dangling build cache..."
          docker builder prune -af || true

      - name: Run Docker Containers
        run: make up-prod
